#!/usr/bin/env bash

usage="Usage: $(basename "$0") [--hybrid-jidt | --hybrid-pw] [STEPS] RUN"
if [[ $# -lt 1 || $# -gt 3 ]]; then
    echo "$usage"
    exit 1
fi
if [[ $1 == "--hybrid-jidt" ]]; then
    hybridJidt=1
    shift
else
    hybridJidt=0
fi
if [[ $1 == "--hybrid-pw" ]]; then
    hybridPw=1
    shift
else
    hybridPw=0
fi
if [[ $# -gt 1 ]]; then
    steps=$1
    shift
    if [[ $steps -le 0 ]]; then
        echo "STEPS must be greater than zero."
        exit 1
    fi
else
    steps=0
fi
run=$1
shift
if [[ ! -e "$run/endStep.txt" ]]; then
    echo "RUN '$run' is not valid."
    exit 1
fi
if [[ $# -gt 0 ]]; then
    echo "$usage"
    exit 1
fi
if [[ $hybridJidt -eq 1 ]]; then
    if [[ $steps -gt 0 ]]; then
        ./scripts/bf2ts.py --steps $steps "$run" | infodynamics Complexity
    else
        ./scripts/bf2ts.py --max-steps 500 "$run" | infodynamics Complexity
    fi
else
    if [[ $hybridPw -eq 1 ]]; then
        directory="timeseries"
    else
        directory="function"
    fi
    for file in $run/brain/$directory/*; do
        if [[ $steps -gt 0 ]]; then
            ./bin/CalcComplexity brainfunction --bare --tile "$file" $steps P
        else
            ./bin/CalcComplexity brainfunction --bare "$file" P
        fi
    done
fi
