#!/usr/bin/env bash

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "Usage: $(basename "$0") [-i] INPUT"
    exit 1
fi
if [[ $1 == "-i" ]]; then
    inPlace=1
    shift
else
    inPlace=0
fi
input=$1
shift
if [[ ! -e "$input" ]]; then
    echo "INPUT '$input' does not exist."
    exit 1
fi
output=$(tempfile -s .pdf)
gs -dBATCH -dNOPAUSE -dQUIET -dSAFER -sDEVICE=pdfwrite -sOutputFile="$output" "$input"
if [[ $inPlace -eq 0 ]]; then
    mv "$input" "$input.bak"
fi
mv "$output" "$input"
