#!/usr/bin/env bash

if [[ $# -lt 3 ]]; then
    echo "Usage: $(basename "$0") SIZE INPUT OUTPUT [PARAMETER]..."
    exit 1
fi
size=$1
shift
input=$1
shift
if [[ ! -e "$input" ]]; then
    echo "INPUT '$input' does not exist."
    exit 1
fi
output=$1
shift
start=1
delta=1
for index in $(seq $#); do
    next_index=$((index + 1))
    case "${!index}" in
        -s)
            start=${!next_index}
            ;;
        -d)
            delta=${!next_index}
            ;;
    esac
done
vf="vflip, drawtext=text='%{eif\:$start+n*$delta\:d}':x=10:y=10:fontcolor=white"
./bin/PwMoviePlayer -f "$input" "$@" -w | ffmpeg \
    -f rawvideo -pix_fmt rgba -s "$size" -r 60 -i pipe:0 \
    -vcodec libx264 -crf 18 -movflags faststart -bf 2 -flags +cgop -g 30 -pix_fmt yuv420p -vf "$vf" -y "$output"
