#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "Usage: $(basename "$0") INPUT OUTPUT [PARAMETER]..."
    exit 1
fi
input=$1
shift
if [[ ! -e "$input" ]]; then
    echo "INPUT '$input' does not exist."
    exit 1
fi
output=$1
shift
start=1
for (( index=1; index <= $#; index++ )); do
    if [[ ${!index} == "-s" ]]; then
        next_index=$((index + 1))
        start=${!next_index}
        break
    fi
done
vf="vflip, drawtext=text=%{n}: start_number=$start: x=10: y=10: fontcolor=white"
./bin/PwMoviePlayer -f "$input" "$@" -w | ffmpeg \
    -f rawvideo -pix_fmt rgba -s 640x480 -r 60 -i pipe:0 \
    -vcodec libx264 -crf 18 -movflags faststart -bf 2 -flags +cgop -g 30 -pix_fmt yuv420p -vf "$vf" -y "$output"
