#!/usr/bin/env bash

if [[ $# -ne 3 ]]; then
    echo "Usage: $(basename "$0") ARCHIVE RUN STAGE"
    exit 1
fi
archive=$1
shift
if [[ -e "$archive" ]]; then
    echo "ARCHIVE '$archive' already exists."
    exit 1
fi
run=$1
shift
if [[ ! -e "$run/endStep.txt" ]]; then
    echo "RUN '$run' is not valid."
    exit 1
fi
stage=$1
shift
tar --ignore-failed-read -czf $archive \
    "$run/gitrevision.txt" \
    "$run/original.wfs" \
    "$run/original.wf" \
    "$run/converted.wf" \
    "$run/normalized.wf" \
    "$run/endStep.txt" \
    "$run/endReason.txt" \
    "$run/BirthsDeaths.log" \
    "$run/lifespans.txt" \
    "$run/brain/synapses"/synapses_*_$stage.txt.gz \
    "$run/genome"
