#!/usr/bin/env bash

if [[ $# -ne 2 ]]; then
    echo "Usage: $(basename "$0") ARCHIVE RUN"
    exit 1
fi
archive=$1
shift
if [[ -e "$archive" ]]; then
    echo "Archive '$archive' already exists."
    exit 1
fi
run=$1
shift
if [[ ! -e "$run/endStep.txt" ]]; then
    echo "Run '$run' is not valid."
    exit 1
fi
tar --ignore-failed-read -czf $archive \
    "$run/gitrevision.txt" \
    "$run/original.wfs" \
    "$run/original.wf" \
    "$run/converted.wf" \
    "$run/normalized.wf" \
    "$run/endStep.txt" \
    "$run/endReason.txt" \
    "$run/BirthsDeaths.log" \
    "$run/lifespans.txt" \
    "$run/brain/synapses" \
    "$run/genome" \
    "$run/passive/brain/synapses" \
    "$run/passive/genome"
