#!/usr/bin/env bash

if [[ $# -lt 3 ]]; then
    echo "Usage: $(basename "$0") WORLDFILE COUNT KEY [--complete] [PARAMETER]..."
    exit 1
fi
worldfile=$1
shift
count=$1
shift
if [[ $count -le 0 ]]; then
    echo "Count must be greater than zero."
    exit 1
fi
key=$1
shift
if [[ -e "runs/$key" ]]; then
    echo "Key '$key' is already in use."
    exit 1
fi
if [[ $1 == "--complete" ]]; then
    complete=1
    shift
else
    complete=0
fi
if [[ $count -gt 1 ]]; then
    mkdir -p "runs/$key"
else
    mkdir -p runs
fi
for index in $(seq 0 $((count - 1))); do
    while true; do
        ./Polyworld --InitSeed "$(date +%s)" "$@" "$worldfile"
        if [[ $complete -eq 1 ]]; then
            if [[ -e run/endReason.txt && $(cat run/endReason.txt) == "MaxSteps" ]]; then
                break
            else
                rm -rf run
            fi
        else
            break
        fi
    done
    if [[ $count -gt 1 ]]; then
        mv run "runs/$key/run-$index"
    else
        mv run "runs/$key"
    fi
done
