#!/usr/bin/env bash

if [[ $# -lt 3 ]]; then
    echo "Usage: $(basename "$0") WORLDFILE COUNT KEY [PARAMETER]..."
    exit 1
fi
worldfile="$1"
count="$2"
if [[ $count -le 0 ]]; then
    echo "Count must be greater than zero."
    exit 1
fi
key="$3"
if [[ -e "runs/$key" ]]; then
    echo "Key '$key' is already in use."
    exit 1
fi
shift 3
if [[ $count -gt 1 ]]; then
    mkdir -p "runs/$key"
fi
for index in `seq 0 $((count - 1))`; do
    ./Polyworld --InitSeed $(date +"%s") "$@" "$worldfile"
    if [[ $count -gt 1 ]]; then
        mv run "runs/$key/run_$index"
    else
        mv run "runs/$key"
    fi
done
