#!/usr/bin/env bash

usage="Usage: $(basename "$0") WORLDFILE RUN START COUNT STAGE [PARAMETER]..."
if [[ $# -lt 5 ]]; then
    echo "$usage"
    exit 1
fi
worldfile=$1
shift
if [[ ! -e "$worldfile" ]]; then
    echo "WORLDFILE '$worldfile' does not exist."
    exit 1
fi
run=$1
shift
if [[ ! -e "$run/endStep.txt" ]]; then
    echo "RUN '$run' is not valid."
    exit 1
fi
start=$1
shift
if [[ $start -le 0 ]]; then
    echo "START must be greater than zero."
    exit 1
fi
count=$1
shift
if [[ $count -le 0 ]]; then
    echo "COUNT must be greater than zero."
    exit 1
fi
stage=$1
shift
genomes=genomeSeeds.txt
synapses=synapseSeeds.txt
truncate -s 0 "$genomes"
truncate -s 0 "$synapses"
for agent in $(seq $start $((start + count - 1))); do
    genome=$(readlink -f "$run/genome/agents/genome_$agent.txt.gz")
    if [[ ! -e "$genome" ]]; then
        echo "Genome file '$genome' does not exist."
        exit 1
    fi
    echo "$genome" >> "$genomes"
    synapse=$(readlink -f "$run/brain/synapses/synapses_${agent}_$stage.txt.gz")
    if [[ ! -e "$synapse" ]]; then
        echo "Synapse file '$synapses' does not exist."
        exit 1
    fi
    echo "$synapse" >> "$synapses"
done
./Polyworld --InitSeed "$(date +%s)" --SeedGenomeFromRun True --SeedSynapsesFromRun True "$@" "$worldfile"
rm "$genomes" "$synapses"
