#!/usr/bin/env bash

if [[ $# -lt 3 ]]; then
    echo "Usage: $(basename "$0") WORLDFILE COUNT KEY [PARAMETER]..."
    exit 1
fi
worldfile="$1"
count="$2"
key="$3"
shift 3
if [[ -e "runs/$key" ]]; then
    echo "Key '$key' is already in use."
    exit 1
fi
mkdir -p "runs/$key"
for index in `seq 0 $((count - 1))`; do
    ./Polyworld --InitSeed $(date +"%s") "$@" "$worldfile"
    mv run "runs/$key/run_$index"
done
