#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "Usage: $(basename "$0") WORLDFILE KEY [PARAMETER]..."
    exit 1
fi
worldfile="$1"
key="$2"
shift 2
if [[ -e "runs/$key" ]]; then
    echo "Key '$key' is already in use."
    exit 1
fi
mkdir -p runs
./Polyworld --InitSeed $(date +"%s") "$@" "$worldfile"
mv run "runs/$key"
